### ISSUE TITLE
Rephrase the description of CALM

### ISSUE THREAD

**Issue by VitoVan** [VitoVan/calm#145]
The current description of CALM is:

> Canvas Aided Lisp Magic: Create canvas-based applications with Lisp and distribute them on Linux, macOS, Windows, and the web.

Another version is:

> A Lisp development environment that enables you to build and distribute canvas based applications as Linux AppImage, macOS Application Bundle, Windows Installer and Web Application.

Which one do you prefer?

@eltociear

**Comment by eltociear** [comment]
@VitoVan 
Personally, I like the current version because it is more "software description" like!

**Comment by VitoVan** [comment]
Good! let's keep it as is then.
